// Generated by CoffeeScript 1.9.2
(function() {
  var app, assert, compile, express, path, server, stylus;

  express = require('express');

  path = require('path');

  assert = require('assert');

  stylus = require('stylus');

  app = express();

  compile = function(str, path) {
    return stylus(str).set('filename', path);
  };

  app.set('views', path.join(__dirname + '/view'));

  app.set('view engine', 'jade');

  app.use(stylus.middleware({
    src: __dirname + '/',
    dest: __dirname + '/',
    force: true,
    compile: compile
  }));

  app.use('/public', express["static"](path.join(__dirname + '/public')));

  app.use('/component', express["static"](path.join(__dirname + '/component')));

  app.use('/bower_components', express["static"](path.join(__dirname + '/bower_components')));

  app.use('/css', express["static"](path.join(__dirname + '/css')));

  app.get('/', function(req, res) {
    return res.render('index');
  });

  app.get('/component/component-header', function(req, res) {
    return res.render('../component/component-header/index.jade');
  });

  app.get('/who', function(req, res) {
    return res.render('who');
  });

  app.get('/contact', function(req, res) {
    return res.render('contact');
  });

  server = app.listen(10, function() {
    var host, port;
    host = server.address().address;
    port = server.address().port;
    return console.log('Listening http://%s:%s', host, port);
  });

}).call(this);
